name: backend_app
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  sqlite3: ^2.4.4
  drift: ^2.2.0
  path: ^1.8.1

dev_dependencies:
  build_runner: ^2.1.7
  drift_dev: ^2.2.0
  http: ^1.1.0
  lints: ^4.0.0
  test: ^1.24.0
